-- ============================================================================
-- Incremental migrations — IDEMPOTENT, safe to run on every deploy.
--
-- complete_schema.sql (pg_dump) is only applied to a FRESH database (db-init
-- skips it once auth_user exists). This file carries the additive changes made
-- after that dump so an EXISTING production database also gets them, with no code
-- change. Every statement is IF NOT EXISTS / IF EXISTS / ADD COLUMN IF NOT EXISTS,
-- so re-running it (including right after a fresh complete_schema load) is a no-op.
--
-- Parent tables referenced here (zones, personnel, pay_period) exist in any
-- deployed POB database.
-- ============================================================================

-- ── Access-control controllers (LAN inBio/C3 panels) + reader ports ──────────
CREATE TABLE IF NOT EXISTS public.access_controllers (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              varchar(100) NOT NULL,
    serial_number     varchar(64),
    model             varchar(64),
    manufacturer      varchar(64) DEFAULT 'ZKTeco',
    ip_address        varchar(45) NOT NULL,
    port              integer NOT NULL DEFAULT 4370,
    comm_password     varchar(64),
    door_count        integer NOT NULL DEFAULT 1,
    status            varchar(20) NOT NULL DEFAULT 'offline',
    last_seen         timestamptz,
    last_error        varchar(255),
    poll_enabled      boolean NOT NULL DEFAULT false,
    poll_interval_sec integer NOT NULL DEFAULT 5,
    notes             text,
    created_at        timestamptz DEFAULT now(),
    updated_at        timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_access_controllers_ip_address ON public.access_controllers (ip_address);
CREATE INDEX IF NOT EXISTS ix_access_controllers_serial_number ON public.access_controllers (serial_number);
ALTER TABLE public.access_controllers ADD COLUMN IF NOT EXISTS location varchar(255);

CREATE TABLE IF NOT EXISTS public.access_readers (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    controller_id integer NOT NULL REFERENCES public.access_controllers(id) ON DELETE CASCADE,
    door_no       integer NOT NULL,
    direction     varchar(5) NOT NULL,
    name          varchar(100),
    zone_id       integer REFERENCES public.zones(id),
    status        varchar(20) NOT NULL DEFAULT 'active',
    last_event_at timestamptz,
    created_at    timestamptz DEFAULT now(),
    updated_at    timestamptz DEFAULT now(),
    CONSTRAINT uq_reader_controller_door_dir UNIQUE (controller_id, door_no, direction)
);
CREATE INDEX IF NOT EXISTS ix_access_readers_controller_id ON public.access_readers (controller_id);
CREATE INDEX IF NOT EXISTS ix_access_readers_zone_id ON public.access_readers (zone_id);

-- ── Payroll: per-employee compensation + statutory IDs ───────────────────────
CREATE TABLE IF NOT EXISTS public.pay_employee_compensation (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id           integer NOT NULL REFERENCES public.personnel(id),
    basic            numeric(14,2) NOT NULL DEFAULT 0,
    housing          numeric(14,2) NOT NULL DEFAULT 0,
    transport        numeric(14,2) NOT NULL DEFAULT 0,
    other_allowances numeric(14,2) NOT NULL DEFAULT 0,
    nhis             numeric(14,2) NOT NULL DEFAULT 0,
    life_assurance   numeric(14,2) NOT NULL DEFAULT 0,
    currency         varchar(3) NOT NULL DEFAULT 'NGN',
    grade            varchar(50),
    nhf_enabled      boolean DEFAULT true,
    tin              varchar(30),
    rsa_pin          varchar(30),
    pfa_name         varchar(100),
    nhf_number       varchar(30),
    tax_state        varchar(50),
    bank_name        varchar(100),
    bank_account_no  varchar(20),
    effective_date   date,
    end_date         date,
    is_active        boolean DEFAULT true,
    created_at       timestamptz DEFAULT now(),
    updated_at       timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_pay_emp_comp_emp_id ON public.pay_employee_compensation (emp_id);

-- ── Payroll: off-cycle adjustments (arrears / bonus / one-off deductions) ─────
CREATE TABLE IF NOT EXISTS public.pay_adjustment (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id     integer NOT NULL REFERENCES public.personnel(id),
    period_id  integer NOT NULL REFERENCES public.pay_period(id),
    name       varchar(80) NOT NULL,
    amount     numeric(14,2) NOT NULL,
    adj_type   varchar(10) NOT NULL DEFAULT 'earning',
    is_taxable boolean DEFAULT true,
    reason     text,
    is_active  boolean DEFAULT true,
    created_by integer,
    created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_pay_adjustment_period ON public.pay_adjustment (period_id, emp_id);

-- ── Payroll: approval actor columns become soft refs (auth is auth_user) ─────
ALTER TABLE public.pay_salary DROP CONSTRAINT IF EXISTS pay_salary_calc_by_fkey;
ALTER TABLE public.pay_salary DROP CONSTRAINT IF EXISTS pay_salary_verified_by_fkey;
ALTER TABLE public.pay_salary DROP CONSTRAINT IF EXISTS pay_salary_approved_by_fkey;

-- ── Integrations: config-driven connector options (SeamlessHR + BC) ──────────
-- Guarded: these config tables may be created lazily by the app on an older DB,
-- so only ALTER when present (never abort the deploy).
DO $$
BEGIN
  IF to_regclass('public.hr_integration_config') IS NOT NULL THEN
    ALTER TABLE public.hr_integration_config ADD COLUMN IF NOT EXISTS options jsonb;
  END IF;
  IF to_regclass('public.bc_integration_config') IS NOT NULL THEN
    ALTER TABLE public.bc_integration_config ADD COLUMN IF NOT EXISTS options jsonb;
  END IF;
END $$;

-- ── Visitor pre-registration: approval_by is the logged-in user (auth_user) ──
-- The approve endpoint records current_user.id (auth_user), matching created_by.
-- Older DBs still point this FK at personnel_employee; repoint it idempotently.
-- The table is normally empty at upgrade; the UPDATE guards any legacy
-- employee-id values so the new FK validates cleanly.
ALTER TABLE public.vis_pre_registration DROP CONSTRAINT IF EXISTS vis_pre_registration_approval_by_fkey;
UPDATE public.vis_pre_registration SET approval_by = NULL
  WHERE approval_by IS NOT NULL AND approval_by NOT IN (SELECT id FROM public.auth_user);
ALTER TABLE public.vis_pre_registration ADD CONSTRAINT vis_pre_registration_approval_by_fkey
  FOREIGN KEY (approval_by) REFERENCES public.auth_user(id);

-- ── Access-control doors: reference a controller + port (not just a terminal) ──
-- Access-control readers are dumb readers wired to a controller, so a door is a
-- (controller, port) unit. Additive columns; terminal_sn kept for legacy T&A doors.
ALTER TABLE public.acc_door ADD COLUMN IF NOT EXISTS controller_id integer REFERENCES public.access_controllers(id);
ALTER TABLE public.acc_door ADD COLUMN IF NOT EXISTS port integer;

-- ── Mustering: directed assembly — a target muster point per event ────────────
-- zone_ids = affected/source zones (who is expected). muster_zone_id = the
-- MUSTER_POINT zone people report TO (headcount via its Horus H1 ADMS reader).
ALTER TABLE public.mustering_event ADD COLUMN IF NOT EXISTS muster_zone_id integer REFERENCES public.zones(id);
CREATE INDEX IF NOT EXISTS ix_mustering_event_muster_zone_id ON public.mustering_event (muster_zone_id);
-- Multiple assembly points per event (personnel go to the nearest); muster_zone_id
-- stays as the primary (= muster_zone_ids[0]) for manual-mark attribution.
ALTER TABLE public.mustering_event ADD COLUMN IF NOT EXISTS muster_zone_ids jsonb DEFAULT '[]'::jsonb;

-- mustering_log.last_punch_area holds a zone NAME (zones.name is varchar(100));
-- the original varchar(20) truncated longer names and broke safe-count attribution.
ALTER TABLE public.mustering_log ALTER COLUMN last_punch_area TYPE varchar(100);
